name: Build gen_snapshot for Android ARM64
on: [workflow_dispatch]
jobs:
  build:
    container:
      image: docker.io/library/debian
    runs-on: ubuntu-latest
    steps:
      - name: Install build tools
        run: |
          apt-get update
          apt-get install --no-install-recommends -y ca-certificates curl git python3 tar
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache depot_tools and Dart SDK sources
        id: cache-dart
        uses: actions/cache@v4
        with:
          path: |
            depot_tools
            dart-sdk
          key: ${{ runner.os }}-debian-dart-3.9.0-final
      - name: Fetch Dart SDK and Android Dependencies
        if: steps.cache-dart.outputs.cache-hit != 'true'
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          export DEPOT_TOOLS_UPDATE=0 PATH=$PWD/depot_tools:$PATH
          mkdir dart-sdk
          cd dart-sdk
          gclient config --name sdk --custom-var download_android_deps=True "https://dart.googlesource.com/sdk.git@3.9.0"
          gclient sync --no-history
      - name: Create custom args.gn for Android build
        run: |
          cd dart-sdk/sdk
          mkdir -p out/ReleaseX64_android_arm64
          echo '
          target_os = "android"
          target_cpu = "arm64"
          host_cpu = "x64"
          is_debug = false
          is_product = true
          dart_vm_product = true
          dart_use_compressed_pointers = true
          is_component_build = false
          is_clang = true
          use_goma = false
          ' > out/ReleaseX64_android_arm64/args.gn
      - name: Build
        run: |
          export DEPOT_TOOLS_UPDATE=0 PATH=$PWD/depot_tools:$PATH
          cd dart-sdk/sdk
          ./tools/build.py --mode release --arch arm64 create_sdk
      - name: Archive the binary
        run: |
          cd dart-sdk/sdk/out/Release*
          tar -czf gen_snapshot.tar.gz gen_snapshot*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gen_snapshot-android-arm64
          path: dart-sdk/sdk/out/Release*/gen_snapshot.tar.gz