name: Build gen_snapshot for Android ARM64
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache depot_tools and Dart SDK sources
        id: cache-dart
        uses: actions/cache@v4
        with:
          path: |
            depot_tools
            dart-sdk-source
          key: ${{ runner.os }}-dart-3.9.0-v7

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential curl git python3-setuptools

      - name: Install depot_tools
        if: steps.cache-dart.outputs.cache-hit != 'true'
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Add depot_tools to PATH
        run: echo "$(pwd)/depot_tools" >> $GITHUB_PATH

      - name: Download Dart 3.9.0 sources and Android dependencies
        if: steps.cache-dart.outputs.cache-hit != 'true'
        run: |
          mkdir dart-sdk-source
          cd dart-sdk-source
          gclient config --name sdk --custom-var download_android_deps=True "https://dart.googlesource.com/sdk.git"
          gclient sync --force --delete_unversioned_trees --no-history
          cd sdk
          git fetch --tags
          git checkout 3.9.0
          cd ..
          gclient sync --force --delete_unversioned_trees --no-history

      - name: Build the Dart SDK for Android ARM64
        run: |
          cd dart-sdk-source/sdk
          python3 ./tools/build.py --mode release --os android --arch arm64 create_sdk

      - name: Archive the binary
        run: |
          cd dart-sdk-source/sdk/out/Release*
          zip gen_snapshot.zip gen_snapshot*

      - name: Upload gen_snapshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: gen_snapshot-android-arm64
          path: dart-sdk-source/sdk/out/Release*/gen_snapshot.zip