name: Build gen_snapshot for Android ARM64 (Based on Official Method)

on: [workflow_dispatch]

jobs:
  build:
    # Запускаемся в стандартной среде Ubuntu. Debian-контейнер для нашей
    # единственной цели - избыточен и только усложнит всё.
    # Главное - это команды, которые мы выполняем.
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl git python3-setuptools

    # --- НОВЫЙ, ПРАВИЛЬНЫЙ ПРОЦЕСС ---

    - name: Install depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$(pwd)/depot_tools" >> $GITHUB_PATH

    - name: Download Dart 3.9.0 sources and Android dependencies
      run: |
        mkdir dart-sdk-source
        cd dart-sdk-source
        
        # ШАГ 1: Конфигурация. Без версии, но с "волшебной" переменной.
        echo "--- [1/3] Configuring gclient with Android deps ---"
        gclient config --name sdk --custom-var download_android_deps=True "https://dart.googlesource.com/sdk.git"
        
        # ШАГ 2: Синхронизация. Скачиваем main ветку.
        echo "--- [2/3] Initial sync to get the repository ---"
        gclient sync --force --delete_unversioned_trees --no-history
        
        # ШАГ 3: Переключение на 3.9.0 и финальная синхронизация зависимостей
        # Мы можем объединить это в один шаг для простоты
        echo "--- [3/3] Switching to 3.9.0 and final sync ---"
        cd sdk
        git fetch --tags # Скачиваем все теги, чтобы git точно нашел 3.9.0
        git checkout 3.9.0
        cd ..
        gclient sync --force --delete_unversioned_trees --no-history

    # --- ИСПОЛЬЗУЕМ ОФИЦИАЛЬНЫЙ СКРИПТ СБОРКИ ---
    - name: Build the Dart SDK for Android ARM64
      run: |
        cd dart-sdk-source/sdk
        # Запускаем официальный скрипт, он сам вызовет gn и ninja с правильными параметрами.
        # Мы просим его собрать create_sdk - это гарантирует, что gen_snapshot будет создан.
        python3 ./tools/build.py --mode release --os android --arch arm64 create_sdk

    - name: Archive the binary
      run: |
        # Находим наш gen_snapshot в папке с результатами
        # Имя может быть gen_snapshot или gen_snapshot_product_android_arm64
        cd dart-sdk-source/sdk/out/ReleaseX64_android_arm64
        zip gen_snapshot.zip gen_snapshot*

    - name: Upload gen_snapshot artifact
      uses: actions/upload-artifact@v4
      with:
        name: gen_snapshot-android-arm64
        path: dart-sdk-source/sdk/out/ReleaseX64_android_arm64/gen_snapshot.zip